module.exports = (app = {}) => `<?xml version="1.0" encoding="utf-8"?>
<plist version="1.0">
  <dict>
    <key>items</key>
    <array>
      <dict>
        <key>assets</key>
        <array>
          <dict>
            <key>kind</key>
            <string>software-package</string>
            <key>url</key>
            <string>${app.url}</string>
          </dict>
          <dict>
            <key>kind</key>
            <string>display-image</string>
            <key>needs-shine</key>
            <true/>
            <key>url</key>
            <string>${app.icon}</string>
          </dict>
        </array>
        <key>metadata</key>
        <dict>
          <key>bundle-identifier</key>
          <string>${app.identifier}</string>
          <key>bundle-version</key>
          <string>${app.version}</string>
          <key>kind</key>
          <string>software</string>
          <key>title</key>
          <string>${app.name}</string>
        </dict>
      </dict>
    </array>
  </dict>
</plist>`